//Author: Tushar Jaiswal
//Creation Date: 06/14/2017

/*Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output: e
Explanation: 'e' is the letter that was added.*/

public class Solution {
    public char findTheDifference(String s, String t) {
        HashMap<Character, Integer> sChars = new HashMap<Character, Integer>();
        HashMap<Character, Integer> tChars = new HashMap<Character, Integer>();
        
        for(char c : s.toCharArray())
        {
            Integer count = sChars.get(c);
            if(count == null)
            {
                sChars.put(c, 1);
            }
            else
            {
                sChars.put(c, count + 1);
            }
        }
        
        for(char c : t.toCharArray())
        {
            Integer count = tChars.get(c);
            if(count == null)
            {
                tChars.put(c, 1);
            }
            else
            {
                tChars.put(c, count + 1);
            }
        }
        
        for(Map.Entry<Character, Integer> entry : tChars.entrySet())
        {
            Character key = entry.getKey();
            if(sChars.containsKey(key))
            {
                if(sChars.get(key) != entry.getValue())
                {
                    return key;
                }
            }
            else
            {
                return key;
            }
        }
        return '0';    
    }
}